spring:
  config:
    import: application-secret.properties

  web:
    domain:
      server: ${SERVER_DOMAIN}
      client: ${CLIENT_DOMAIN}
      client-local: ${CLIENT_DOMAIN_LOCAL}
    resources:
      add-mappings: false

  security:
    oauth2:
      client:
        naver:
          client-id: ${DEV_OAUTH2_NAVER_ID}
          client-secret: ${DEV_OAUTH2_NAVER_SECRET}
          redirect-uri: ${OAUTH2_NAVER_REDIRECT_URL}
          state: ${OAUTH2_NAVER_STATE}
          user-info-uri: ${OAUTH2_NAVER_USER_INFO_URL}
          token-uri:
            host: ${OAUTH2_NAVER_TOKEN_URI_HOST}
            path: ${OAUTH2_NAVER_TOKEN_URI_PATH}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_HOST}
    password: ${DEV_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379


aws-property:
  access-key: ${DEV_AWS_ACCESS_KEY}
  secret-key: ${DEV_AWS_SECRET_KEY}
  aws-region: ${DEV_AWS_REGION}
  s3-bucket-name: ${DEV_AWS_BUCKET_NAME}
  distribution-domain: ${DEV_AWS_DISTRIBUTION_DOMAIN}
  private-key-file-path: ${DEV_AWS_PRIVATE_KEY_FILE_PATH}
  key-pair-id: ${DEV_AWS_KEY_PAIR_ID}


jwt:
  secretKey: ${DEV_JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    header: ${JWT_ACCESS_TOKEN_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
    header: ${JWT_REFRESH_TOKEN_HEADER}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true