spring:
  config:
    import: application-secret.properties

  web:
    domain :
      server : ${SERVER_DOMAIN}
      client : ${CLIENT_DOMAIN}
      client-local : ${CLIENT_DOMAIN_LOCAL}
    resources:
      add-mappings: false

  security:
    oauth2:
      client:
        naver:
          client-id: ${DEV_OAUTH2_NAVER_ID}
          client-secret: ${DEV_OAUTH2_NAVER_SECRET}
          redirect-uri: ${DEV_OAUTH2_NAVER_REDIRECT_URL}
          state: ${DEV_OAUTH2_NAVER_STATE}
          user-info-uri: ${DEV_OAUTH2_NAVER_USER_INFO_URL}
          token-uri:
            host: ${DEV_OAUTH2_NAVER_TOKEN_URI_HOST}
            path: ${DEV_OAUTH2_NAVER_TOKEN_URI_PATH}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nonsoolmate-local-db;DATABASE_TO_UPPER=FALSE;mode=mysql  # H2 접속 정보 (전부 소문자로 지정)
    username: sa
    password:

aws-property:
  access-key: ${DEV_AWS_ACCESS_KEY}
  secret-key: ${DEV_AWS_SECRET_KEY}
  aws-region: ${DEV_AWS_REGION}
  s3-bucket-name: ${DEV_AWS_BUCKET_NAME}
  distribution-domain: ${DEV_AWS_DISTRIBUTION_DOMAIN}
  private-key-file-path: ${DEV_AWS_PRIVATE_KEY_FILE_PATH}
  key-pair-id: ${DEV_AWS_KEY_PAIR_ID}

jwt:
  secretKey:  ${DEV_JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    header: ${JWT_ACCESS_TOKEN_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
    header: ${JWT_REFRESH_TOKEN_HEADER}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true