spring:
  config:
    import: application-secret.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_HOST}
    password: ${PROD_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

logging:
  discord:
    webhook-uri: ${PROD_DISCORD_WEB_HOOK_URL}

toss:
  billing:
    api-key: ${LIVE_TOSS_BILLING_API_KEY}

coupon:
  secret: ${COUPON_SECRET}