spring:
  config:
    import: application-secret.properties

  security:
    oauth2:
      client:
        naver:
          client-id: ${PROD_OAUTH2_NAVER_ID}
          client-secret: ${PROD_OAUTH2_NAVER_SECRET}
          redirect-uri: ${OAUTH2_NAVER_REDIRECT_URL}
          state: ${OAUTH2_NAVER_STATE}
          user-info-uri: ${OAUTH2_NAVER_USER_INFO_URL}
          token-uri:
            host: ${OAUTH2_NAVER_TOKEN_URI_HOST}
            path: ${OAUTH2_NAVER_TOKEN_URI_PATH}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_HOST}
    password: ${PROD_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: smtp.naver.com
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws-property:
  access-key: ${PROD_AWS_ACCESS_KEY}
  secret-key: ${PROD_AWS_SECRET_KEY}
  aws-region: ${PROD_AWS_REGION}
  s3-bucket-name: ${PROD_AWS_BUCKET_NAME}
  distribution-domain: ${PROD_AWS_DISTRIBUTION_DOMAIN}
  private-key-file-path: ${PROD_AWS_PRIVATE_KEY_FILE_PATH}
  key-pair-id: ${PROD_AWS_KEY_PAIR_ID}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

toss:
  billing:
    api-key: ${LIVE_TOSS_BILLING_API_KEY}

coupon:
  secret: ${COUPON_SECRET}