name: NONSOOLMATE DEV CD

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy-cd:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - name: 설정 파일 생성
      run: |
        echo "${{ secrets.SECRET_PROPERTIES }}" > application-secret.properties
        echo "${{ secrets.CLOUDFRONT_PRIVATE_KEY }}" > cloudfront-private-key.pem
    - name: dev 서버 무중단 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          mkdir -p ~/nonsoolmate-server/nonsoolmateServer/src/main/resources
          scp application-secret.properties ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.REMOTE_SSH_HOST }}:~/nonsoolmate-server/nonsoolmateServer/src/main/resources/application-secret.properties
          mkdir -p ~/nonsoolmate-server/nonsoolmateServer/src/main/resources/key
          scp cloudfront-private-key.pem ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.REMOTE_SSH_HOST }}:~/nonsoolmate-server/nonsoolmateServer/src/main/resources/key/cloudfront-private-key.pem
          cd ~/nonsoolmate-server
          git pull origin dev
          cd ~/nonsoolmate-server/nonsoolmateServer
          ./gradlew clean build
          cd ~/app/nonstop
          ./deploy.sh

